apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mesgboard
spec:
  replicans: 3 # 错误所在位置 正确语法为replicas
  selector:
    matchLabels:
      app: mesgboard
  template: 
    metadata: 
      labels:
        app: mesgboard
    spec: 
      containers:
      - name: mesgboard
        image: mesgboard/mesgboard:1
        ports: 
        - containerPort: 80
        
