apiVersion: apps/vbeta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template: 
    metadata: 
      labels:
        app: mysql
    spec: 
      containers:
      - name: mysql
        image: mesgboard/mysql:1
        ports: 
        - containerPort: 3306
        
